spring.application.name=demo

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/RouteGuard}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.h2.console.enabled=false

routeguard.warning-distance-meters=100
routeguard.critical-distance-meters=300
routeguard.gps-stale-seconds=180
routeguard.alert-cooldown-seconds=300
routeguard.gps-update-interval-ms=3000
